openapi: 3.0.3
info:
  title: photon-indexer
  description: Solana indexer for general compression
  license:
    name: Apache-2.0
  version: 0.19.0
servers:
- url: http://127.0.0.1
paths:
  /:
    summary: getIndexerSlot
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - jsonrpc
              - id
              - method
              properties:
                id:
                  type: string
                  description: An ID to identify the request.
                  enum:
                  - test-account
                jsonrpc:
                  type: string
                  description: The version of the JSON-RPC protocol.
                  enum:
                  - '2.0'
                method:
                  type: string
                  description: The name of the method to invoke.
                  enum:
                  - getIndexerSlot
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: integer
                default: 100
                example: 100
        '429':
          description: Exceeded rate limit.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: The server encountered an unexpected condition that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Account:
      type: object
      required:
      - hash
      - owner
      - lamports
      - tree
      - leafIndex
      - slotCreated
      properties:
        address:
          $ref: '#/components/schemas/SerializablePubkey'
        data:
          $ref: '#/components/schemas/AccountData'
        hash:
          $ref: '#/components/schemas/Hash'
        lamports:
          $ref: '#/components/schemas/UnsignedInteger'
        leafIndex:
          $ref: '#/components/schemas/UnsignedInteger'
        owner:
          $ref: '#/components/schemas/SerializablePubkey'
        seq:
          $ref: '#/components/schemas/UnsignedInteger'
        slotCreated:
          $ref: '#/components/schemas/UnsignedInteger'
        tree:
          $ref: '#/components/schemas/SerializablePubkey'
      additionalProperties: false
    AccountData:
      type: object
      required:
      - discriminator
      - data
      - dataHash
      properties:
        data:
          $ref: '#/components/schemas/Base64String'
        dataHash:
          $ref: '#/components/schemas/Hash'
        discriminator:
          $ref: '#/components/schemas/UnsignedInteger'
      additionalProperties: false
    AccountList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Account'
      additionalProperties: false
    AccountState:
      type: string
      enum:
      - initialized
      - frozen
    AccountWithOptionalTokenData:
      type: object
      required:
      - account
      properties:
        account:
          $ref: '#/components/schemas/Account'
        optional_token_data:
          $ref: '#/components/schemas/TokenData'
    Base58String:
      type: string
      description: A base 58 encoded string.
      default: 3J98t1WpEZ73CNm
      example: 3J98t1WpEZ73CNm
    Base64String:
      type: string
      description: A base 64 encoded string.
      default: SGVsbG8sIFdvcmxkIQ==
      example: SGVsbG8sIFdvcmxkIQ==
    Context:
      type: object
      required:
      - slot
      properties:
        slot:
          type: integer
          default: 100
          example: 100
    Hash:
      type: string
      description: A 32-byte hash represented as a base58 string.
      example: 1111111HuCLMZX6paToMCre2czPNGS3SBpcrqVzHV
    Limit:
      type: integer
      format: int64
      minimum: 0
    MerkleProofWithContext:
      type: object
      required:
      - proof
      - leafIndex
      - hash
      - merkleTree
      - rootSeq
      properties:
        hash:
          $ref: '#/components/schemas/Hash'
        leafIndex:
          type: integer
          format: int32
          minimum: 0
        merkleTree:
          $ref: '#/components/schemas/SerializablePubkey'
        proof:
          type: array
          items:
            $ref: '#/components/schemas/Hash'
        rootSeq:
          type: integer
          format: int64
          minimum: 0
      additionalProperties: false
    PaginatedAccountList:
      type: object
      required:
      - items
      properties:
        cursor:
          $ref: '#/components/schemas/Hash'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Account'
      additionalProperties: false
    PaginatedSignatureInfoList:
      type: object
      required:
      - items
      properties:
        cursor:
          type: string
          nullable: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/SignatureInfo'
    SerializablePubkey:
      type: string
      description: A Solana public key represented as a base58 string.
      default: 1111111HVrjNTDp7PzvXmiZ1Cf4t9AFogZg9bv9y9
      example: 1111111HVrjNTDp7PzvXmiZ1Cf4t9AFogZg9bv9y9
    SerializableSignature:
      type: string
      description: A Solana transaction signature.
      default: 5J8H5sTvEhnGcB4R8K1n7mfoiWUD9RzPVGES7e3WxC7c
      example: 5J8H5sTvEhnGcB4R8K1n7mfoiWUD9RzPVGES7e3WxC7c
    SignatureInfo:
      type: object
      required:
      - signature
      - slot
      - blockTime
      properties:
        blockTime:
          $ref: '#/components/schemas/UnixTimestamp'
        signature:
          $ref: '#/components/schemas/SerializableSignature'
        slot:
          $ref: '#/components/schemas/UnsignedInteger'
    SignatureInfoList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SignatureInfo'
    TokenAcccount:
      type: object
      required:
      - account
      - tokenData
      properties:
        account:
          $ref: '#/components/schemas/Account'
        tokenData:
          $ref: '#/components/schemas/TokenData'
      additionalProperties: false
    TokenAccountBalance:
      type: object
      required:
      - amount
      properties:
        amount:
          $ref: '#/components/schemas/UnsignedInteger'
      additionalProperties: false
    TokenAccountList:
      type: object
      required:
      - items
      properties:
        cursor:
          $ref: '#/components/schemas/Base58String'
        items:
          type: array
          items:
            $ref: '#/components/schemas/TokenAcccount'
    TokenBalance:
      type: object
      required:
      - mint
      - balance
      properties:
        balance:
          $ref: '#/components/schemas/UnsignedInteger'
        mint:
          $ref: '#/components/schemas/SerializablePubkey'
    TokenBalanceList:
      type: object
      required:
      - token_balances
      properties:
        cursor:
          type: string
          nullable: true
        token_balances:
          type: array
          items:
            $ref: '#/components/schemas/TokenBalance'
    TokenData:
      type: object
      required:
      - mint
      - owner
      - amount
      - state
      - delegatedAmount
      properties:
        amount:
          $ref: '#/components/schemas/UnsignedInteger'
        delegate:
          $ref: '#/components/schemas/SerializablePubkey'
        delegatedAmount:
          $ref: '#/components/schemas/UnsignedInteger'
        isNative:
          $ref: '#/components/schemas/UnsignedInteger'
        mint:
          $ref: '#/components/schemas/SerializablePubkey'
        owner:
          $ref: '#/components/schemas/SerializablePubkey'
        state:
          $ref: '#/components/schemas/AccountState'
    UnixTimestamp:
      type: integer
      description: An Unix timestamp (seconds)
      default: 1714081554
      example: 1714081554
    UnsignedInteger:
      type: integer
      default: 100
      example: 100
