openapi: 3.0.3
info:
  title: photon-indexer
  description: Solana indexer for general compression
  license:
    name: Apache-2.0
  version: 0.38.0
servers:
- url: https://devnet.helius-rpc.com?api-key=<api_key>
paths:
  /:
    summary: getIndexerSlot
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - jsonrpc
              - id
              - method
              properties:
                id:
                  type: string
                  description: An ID to identify the request.
                  enum:
                  - test-account
                jsonrpc:
                  type: string
                  description: The version of the JSON-RPC protocol.
                  enum:
                  - '2.0'
                method:
                  type: string
                  description: The name of the method to invoke.
                  enum:
                  - getIndexerSlot
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: integer
                default: 100
                example: 100
components: {}
