openapi: 3.0.3
info:
  title: photon-indexer
  description: Solana indexer for general compression
  license:
    name: Apache-2.0
  version: 0.21.0
servers:
- url: http://127.0.0.1
paths:
  /:
    summary: getLatestCompressionSignatures
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - jsonrpc
              - id
              - method
              - params
              properties:
                id:
                  type: string
                  description: An ID to identify the request.
                  enum:
                  - test-account
                jsonrpc:
                  type: string
                  description: The version of the JSON-RPC protocol.
                  enum:
                  - '2.0'
                method:
                  type: string
                  description: The name of the method to invoke.
                  enum:
                  - getLatestCompressionSignatures
                params:
                  type: object
                  properties:
                    cursor:
                      type: string
                      nullable: true
                    limit:
                      allOf:
                      - $ref: '#/components/schemas/Limit'
                      nullable: true
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                required:
                - context
                - value
                properties:
                  context:
                    $ref: '#/components/schemas/Context'
                  value:
                    $ref: '#/components/schemas/PaginatedSignatureInfoList'
        '429':
          description: Exceeded rate limit.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: The server encountered an unexpected condition that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Account:
      type: object
      required:
      - hash
      - owner
      - lamports
      - tree
      - leafIndex
      - seq
      - slotCreated
      properties:
        address:
          $ref: '#/components/schemas/SerializablePubkey'
        data:
          $ref: '#/components/schemas/AccountData'
        hash:
          $ref: '#/components/schemas/Hash'
        lamports:
          $ref: '#/components/schemas/UnsignedInteger'
        leafIndex:
          $ref: '#/components/schemas/UnsignedInteger'
        owner:
          $ref: '#/components/schemas/SerializablePubkey'
        seq:
          $ref: '#/components/schemas/UnsignedInteger'
        slotCreated:
          $ref: '#/components/schemas/UnsignedInteger'
        tree:
          $ref: '#/components/schemas/SerializablePubkey'
      additionalProperties: false
    AccountData:
      type: object
      required:
      - discriminator
      - data
      - dataHash
      properties:
        data:
          $ref: '#/components/schemas/Base64String'
        dataHash:
          $ref: '#/components/schemas/Hash'
        discriminator:
          $ref: '#/components/schemas/UnsignedInteger'
      additionalProperties: false
    AccountList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Account'
            nullable: true
      additionalProperties: false
    AccountState:
      type: string
      enum:
      - initialized
      - frozen
    AccountWithOptionalTokenData:
      type: object
      required:
      - account
      properties:
        account:
          $ref: '#/components/schemas/Account'
        optional_token_data:
          $ref: '#/components/schemas/TokenData'
    Base58String:
      type: string
      description: A base 58 encoded string.
      default: 3J98t1WpEZ73CNm
      example: 3J98t1WpEZ73CNm
    Base64String:
      type: string
      description: A base 64 encoded string.
      default: SGVsbG8sIFdvcmxkIQ==
      example: SGVsbG8sIFdvcmxkIQ==
    CompressedProof:
      type: object
      required:
      - a
      - b
      - c
      properties:
        a:
          type: string
          format: binary
        b:
          type: string
          format: binary
        c:
          type: string
          format: binary
    CompressedProofWithContext:
      type: object
      required:
      - compressedProof
      - roots
      - rootIndices
      - leafIndices
      - leaves
      - merkleTrees
      properties:
        compressedProof:
          $ref: '#/components/schemas/CompressedProof'
        leafIndices:
          type: array
          items:
            type: integer
            format: int32
            minimum: 0
        leaves:
          type: array
          items:
            type: string
        merkleTrees:
          type: array
          items:
            type: string
        rootIndices:
          type: array
          items:
            type: integer
            format: int64
            minimum: 0
        roots:
          type: array
          items:
            type: string
    Context:
      type: object
      required:
      - slot
      properties:
        slot:
          type: integer
          default: 100
          example: 100
    Hash:
      type: string
      description: A 32-byte hash represented as a base58 string.
      example: 1111111H6X8PLvXQDY3iLaTynKkQ1tUBBJjSNLKeo
    Limit:
      type: integer
      format: int64
      minimum: 0
    MerkleContextWithNewAddressProof:
      type: object
      required:
      - root
      - address
      - lower_range_address
      - higher_range_address
      - leaf_index
      - proof
      - merkle_tree
      - root_seq
      - low_element_leaf_index
      properties:
        address:
          $ref: '#/components/schemas/SerializablePubkey'
        higher_range_address:
          $ref: '#/components/schemas/SerializablePubkey'
        leaf_index:
          type: integer
          format: int32
          minimum: 0
        low_element_leaf_index:
          type: integer
          format: int32
          minimum: 0
        lower_range_address:
          $ref: '#/components/schemas/SerializablePubkey'
        merkle_tree:
          $ref: '#/components/schemas/SerializablePubkey'
        proof:
          type: array
          items:
            $ref: '#/components/schemas/Hash'
        root:
          $ref: '#/components/schemas/Hash'
        root_seq:
          type: integer
          format: int64
          minimum: 0
    MerkleProofWithContext:
      type: object
      required:
      - proof
      - root
      - leafIndex
      - hash
      - merkleTree
      - rootSeq
      properties:
        hash:
          $ref: '#/components/schemas/Hash'
        leafIndex:
          type: integer
          format: int32
          minimum: 0
        merkleTree:
          $ref: '#/components/schemas/SerializablePubkey'
        proof:
          type: array
          items:
            $ref: '#/components/schemas/Hash'
        root:
          $ref: '#/components/schemas/Hash'
        rootSeq:
          type: integer
          format: int64
          minimum: 0
      additionalProperties: false
    PaginatedAccountList:
      type: object
      required:
      - items
      properties:
        cursor:
          $ref: '#/components/schemas/Hash'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Account'
      additionalProperties: false
    PaginatedSignatureInfoList:
      type: object
      required:
      - items
      properties:
        cursor:
          type: string
          nullable: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/SignatureInfo'
    SerializablePubkey:
      type: string
      description: A Solana public key represented as a base58 string.
      default: 1111111GhBXQEdEh35AtuSNxMzRutcgYg3nj8kVLT
      example: 1111111GhBXQEdEh35AtuSNxMzRutcgYg3nj8kVLT
    SerializableSignature:
      type: string
      description: A Solana transaction signature.
      default: 5J8H5sTvEhnGcB4R8K1n7mfoiWUD9RzPVGES7e3WxC7c
      example: 5J8H5sTvEhnGcB4R8K1n7mfoiWUD9RzPVGES7e3WxC7c
    SignatureInfo:
      type: object
      required:
      - signature
      - slot
      - blockTime
      properties:
        blockTime:
          $ref: '#/components/schemas/UnixTimestamp'
        signature:
          $ref: '#/components/schemas/SerializableSignature'
        slot:
          $ref: '#/components/schemas/UnsignedInteger'
    SignatureInfoList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SignatureInfo'
    TokenAcccount:
      type: object
      required:
      - account
      - tokenData
      properties:
        account:
          $ref: '#/components/schemas/Account'
        tokenData:
          $ref: '#/components/schemas/TokenData'
      additionalProperties: false
    TokenAccountBalance:
      type: object
      required:
      - amount
      properties:
        amount:
          $ref: '#/components/schemas/UnsignedInteger'
      additionalProperties: false
    TokenAccountList:
      type: object
      required:
      - items
      properties:
        cursor:
          $ref: '#/components/schemas/Base58String'
        items:
          type: array
          items:
            $ref: '#/components/schemas/TokenAcccount'
    TokenBalance:
      type: object
      required:
      - mint
      - balance
      properties:
        balance:
          $ref: '#/components/schemas/UnsignedInteger'
        mint:
          $ref: '#/components/schemas/SerializablePubkey'
    TokenBalanceList:
      type: object
      required:
      - token_balances
      properties:
        cursor:
          type: string
          nullable: true
        token_balances:
          type: array
          items:
            $ref: '#/components/schemas/TokenBalance'
    TokenData:
      type: object
      required:
      - mint
      - owner
      - amount
      - state
      - delegatedAmount
      properties:
        amount:
          $ref: '#/components/schemas/UnsignedInteger'
        delegate:
          $ref: '#/components/schemas/SerializablePubkey'
        delegatedAmount:
          $ref: '#/components/schemas/UnsignedInteger'
        isNative:
          $ref: '#/components/schemas/UnsignedInteger'
        mint:
          $ref: '#/components/schemas/SerializablePubkey'
        owner:
          $ref: '#/components/schemas/SerializablePubkey'
        state:
          $ref: '#/components/schemas/AccountState'
    UnixTimestamp:
      type: integer
      description: An Unix timestamp (seconds)
      default: 1714081554
      example: 1714081554
    UnsignedInteger:
      type: integer
      default: 100
      example: 100
