use std::sync::Arc;

use function_name::named;
use futures::{pin_mut, StreamExt};
use photon_indexer::api::method::interface::{
    GetAccountInterfaceRequest, GetMultipleAccountInterfacesRequest,
};
use photon_indexer::common::typedefs::serializable_pubkey::SerializablePubkey;
use photon_indexer::dao::generated::token_accounts;
use photon_indexer::ingester::index_block;
use photon_indexer::ingester::typedefs::block_info::{BlockInfo, BlockMetadata};
use sea_orm::{ActiveModelTrait, ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter, Set};
use serial_test::serial;
use solana_client::nonblocking::rpc_client::RpcClient;
use solana_program_pack::Pack;
use spl_token_interface::state::Account as SplTokenAccount;

use crate::utils::*;

/// Directory containing interface test transaction data.
/// Generated by forester's test_indexer_interface test.
const INTERFACE_TEST_DATA_DIR: &str = "indexer_interface";

async fn interface_lookup_addresses(
    db_conn: &DatabaseConnection,
) -> (
    SerializablePubkey,
    SerializablePubkey,
) {
    let row = token_accounts::Entity::find()
        .filter(token_accounts::Column::Spent.eq(false))
        .one(db_conn)
        .await
        .expect("token_accounts query should succeed")
        .expect("expected at least one unspent token account in test data");

    let token_owner = SerializablePubkey::try_from(row.owner.clone())
        .expect("token_accounts.owner must be a valid pubkey");
    let ata_owner = SerializablePubkey::new_unique();

    let mut model: token_accounts::ActiveModel = row.into();
    model.ata_owner = Set(Some(ata_owner.to_bytes_vec()));
    model
        .update(db_conn)
        .await
        .expect("updating ata_owner for test fixture should succeed");

    (ata_owner, token_owner)
}

/// Helper to set up indexing methodologies for interface tests.
fn all_indexing_methodologies_for_interface(
    db_conn: Arc<DatabaseConnection>,
    rpc_client: Arc<RpcClient>,
    txns: &[&str],
) -> impl futures::Stream<Item = ()> {
    let txs = txns.iter().map(|x| x.to_string()).collect::<Vec<String>>();
    async_stream::stream! {
        reset_tables(db_conn.as_ref()).await.unwrap();
        populate_test_tree_metadata(db_conn.as_ref()).await;
        index_block(
            db_conn.as_ref(),
            &BlockInfo {
                metadata: BlockMetadata {
                    slot: 0,
                    ..Default::default()
                },
                ..Default::default()
            },
            &rpc_client,
        )
        .await
        .unwrap();

        for tx in &txs {
            index_transaction(INTERFACE_TEST_DATA_DIR, db_conn.clone(), rpc_client.clone(), tx).await;
        }
        yield ();
    }
}

/// Test getAccountInterface resolves compressed token accounts by token owner pubkey.
#[named]
#[rstest]
#[tokio::test]
#[serial]
async fn test_get_account_interface_token_owner(
    #[values(DatabaseBackend::Sqlite, DatabaseBackend::Postgres)] db_backend: DatabaseBackend,
) {
    let name = trim_test_name(function_name!());
    let setup = setup_with_options(
        name.clone(),
        TestSetupOptions {
            network: Network::Localnet,
            db_backend,
        },
    )
    .await;

    // Mint compressed tokens to Bob and Charlie
    let mint_tokens_tx =
        "2YTv5hjSmRAgfwoNHdc4DRDFWW7fqQb57f9s8Rxtu9u6jA2hDxNxEWoiybvn4p7ua2nw3scYeNo6htYCSuBYviFd";

    let txs = [mint_tokens_tx];
    let indexing =
        all_indexing_methodologies_for_interface(setup.db_conn.clone(), setup.client.clone(), &txs);
    pin_mut!(indexing);

    while let Some(_) = indexing.next().await {
        let (ata_owner, token_owner) = interface_lookup_addresses(setup.db_conn.as_ref()).await;

        // Token owner lookup should resolve compressed token accounts.
        let result = setup
            .api
            .get_account_interface(GetAccountInterfaceRequest {
                address: token_owner,
                commitment: None,
            })
            .await
            .unwrap();

        let value = result.value.clone().expect("expected interface value");
        let cold = value.cold.expect("expected compressed token accounts");
        assert!(
            !cold.is_empty(),
            "expected at least one compressed token account"
        );

        // ATA-owner-only lookup must not resolve via cold token linkage.
        let ata_owner_result = setup
            .api
            .get_account_interface(GetAccountInterfaceRequest {
                address: ata_owner,
                commitment: None,
            })
            .await
            .unwrap();
        assert!(ata_owner_result.value.is_none());
    }
}

/// Test ATA-mode compressed lookup:
/// - token_accounts.owner (ATA pubkey) is used for lookup
/// - token_accounts.ata_owner (wallet pubkey) is used as synthetic SPL owner
#[named]
#[rstest]
#[tokio::test]
#[serial]
async fn test_get_account_interface_ata_mode_owner_lookup_and_wallet_owner_synthesis(
    #[values(DatabaseBackend::Sqlite, DatabaseBackend::Postgres)] db_backend: DatabaseBackend,
) {
    let name = trim_test_name(function_name!());
    let setup = setup_with_options(
        name.clone(),
        TestSetupOptions {
            network: Network::Localnet,
            db_backend,
        },
    )
    .await;

    let mint_tokens_tx =
        "2YTv5hjSmRAgfwoNHdc4DRDFWW7fqQb57f9s8Rxtu9u6jA2hDxNxEWoiybvn4p7ua2nw3scYeNo6htYCSuBYviFd";

    let txs = [mint_tokens_tx];
    let indexing =
        all_indexing_methodologies_for_interface(setup.db_conn.clone(), setup.client.clone(), &txs);
    pin_mut!(indexing);

    while let Some(_) = indexing.next().await {
        let row = token_accounts::Entity::find()
            .filter(token_accounts::Column::Spent.eq(false))
            .one(setup.db_conn.as_ref())
            .await
            .expect("token_accounts query should succeed")
            .expect("expected at least one unspent token account in test data");

        let lookup_ata = SerializablePubkey::new_unique();
        let wallet_owner = SerializablePubkey::new_unique();

        let mut model: token_accounts::ActiveModel = row.into();
        model.owner = Set(lookup_ata.to_bytes_vec());
        model.ata_owner = Set(Some(wallet_owner.to_bytes_vec()));
        model
            .update(setup.db_conn.as_ref())
            .await
            .expect("updating token owner/ata_owner fixture should succeed");

        let result = setup
            .api
            .get_account_interface(GetAccountInterfaceRequest {
                address: lookup_ata,
                commitment: None,
            })
            .await
            .unwrap();

        let value = result.value.expect("expected interface value");
        let cold = value.cold.expect("expected compressed token accounts");
        assert!(
            !cold.is_empty(),
            "expected cold token accounts for ATA-mode owner lookup"
        );

        let parsed = SplTokenAccount::unpack(&value.account.data.0)
            .expect("expected synthesized SPL token account bytes");
        assert_eq!(
            SerializablePubkey::from(parsed.owner.to_bytes()),
            wallet_owner,
            "synthetic SPL owner should come from ata_owner wallet mapping"
        );
    }
}

/// Test getMultipleAccountInterfaces with mixed addresses.
///
/// Tests batch lookup with addresses that don't exist in compressed DB.
#[named]
#[rstest]
#[tokio::test]
#[serial]
async fn test_get_multiple_account_interfaces(
    #[values(DatabaseBackend::Sqlite, DatabaseBackend::Postgres)] db_backend: DatabaseBackend,
) {
    let name = trim_test_name(function_name!());
    let setup = setup_with_options(
        name.clone(),
        TestSetupOptions {
            network: Network::Localnet,
            db_backend,
        },
    )
    .await;

    // Mint compressed tokens to Bob and Charlie
    let mint_tokens_tx =
        "2YTv5hjSmRAgfwoNHdc4DRDFWW7fqQb57f9s8Rxtu9u6jA2hDxNxEWoiybvn4p7ua2nw3scYeNo6htYCSuBYviFd";

    // Use a random address that definitely doesn't exist on-chain or compressed
    // (default pubkey 11111... is the system program which exists on-chain)
    let nonexistent_address =
        SerializablePubkey::try_from("DeadDeadDeadDeadDeadDeadDeadDeadDeadDeadDead").unwrap();

    let txs = [mint_tokens_tx];
    let indexing =
        all_indexing_methodologies_for_interface(setup.db_conn.clone(), setup.client.clone(), &txs);
    pin_mut!(indexing);

    while let Some(_) = indexing.next().await {
        let (first_ata_owner, token_owner) = interface_lookup_addresses(setup.db_conn.as_ref()).await;

        // Test getMultipleAccountInterfaces
        let result = setup
            .api
            .get_multiple_account_interfaces(GetMultipleAccountInterfacesRequest {
                addresses: vec![
                    token_owner,
                    token_owner,
                    first_ata_owner,
                    nonexistent_address,
                ],
                commitment: None,
            })
            .await
            .unwrap();

        // Token owner pubkeys resolve, while ata-owner-only and nonexistent don't.
        assert_eq!(result.value.len(), 4);
        assert!(result.value[0]
            .as_ref()
            .and_then(|v| v.cold.as_ref())
            .is_some_and(|cold| !cold.is_empty()));
        assert!(result.value[1]
            .as_ref()
            .and_then(|v| v.cold.as_ref())
            .is_some_and(|cold| !cold.is_empty()));
        assert!(result.value[2].is_none());
        assert!(result.value[3].is_none());
    }
}

/// Test batch size validation for getMultipleAccountInterfaces.
#[named]
#[rstest]
#[tokio::test]
#[serial]
async fn test_get_multiple_account_interfaces_validation(
    #[values(DatabaseBackend::Sqlite, DatabaseBackend::Postgres)] db_backend: DatabaseBackend,
) {
    let name = trim_test_name(function_name!());
    let setup = setup_with_options(
        name.clone(),
        TestSetupOptions {
            network: Network::Localnet,
            db_backend,
        },
    )
    .await;

    // Test empty request - should fail
    let empty_result = setup
        .api
        .get_multiple_account_interfaces(GetMultipleAccountInterfacesRequest {
            addresses: vec![],
            commitment: None,
        })
        .await;

    assert!(empty_result.is_err());

    // Test over limit - should fail (MAX_BATCH_SIZE is 100)
    let over_limit: Vec<SerializablePubkey> =
        (0..101).map(|_| SerializablePubkey::default()).collect();

    let over_limit_result = setup
        .api
        .get_multiple_account_interfaces(GetMultipleAccountInterfacesRequest {
            addresses: over_limit,
            commitment: None,
        })
        .await;

    assert!(over_limit_result.is_err());
}

/*
## Test Data

Test data is generated by forester's test_indexer_interface test:
  cd light-protocol/forester && cargo test -p forester --test test_indexer_interface -- --nocapture

Then exported using:
  cargo xtask export-photon-test-data --test-name indexer_interface

The test creates:
1. SPL Mint (on-chain) - standard mint for token operations
2. Compressed token accounts (via mint_to) - these have NO address field
3. Registered v2 address in batched address tree - for address tree verification
4. Compressible token accounts - on-chain accounts that can be compressed

Transaction files are stored in tests/data/transactions/indexer_interface/

*/
